- name: Extract project
  run: unzip TamilBibleAPK.zip

- name: Grant gradlew permission
  run: chmod +x TamilBibleAPK/gradlew

- name: Build APK
  run: cd TamilBibleAPK && ./gradlew assembleDebug --stacktrace

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: app-debug
    path: TamilBibleAPK/app/build/outputs/apk/debug/app-debug.apk
